# Site settings
title: Moiz K. Malik - Bushwick, Brooklyn
email: moiz@moiz.org
description: > # this means to ignore newlines until "baseurl:"
  I'm Moiz, a hacker and designer currently living in Bushwick, Brooklyn. I like to build things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://moiz.org" # the base hostname & protocol for your site
twitter_username: moizkmalik
github_username:  moizk

# Build settings
markdown: kramdown
